### ISSUE TITLE
--paired 

### ISSUE THREAD

**Issue by renny817** [genomematt/xenomapper#14]
Hello,

I have successfully ran xenomapper on paired WGS data aligned using bwa mem hs37d5: 

```
xenomapper --primary_bam "$PRIMARY".merged.dedup.rnsort.test.bam     --secondary_bam "$SECONDARY".merged.dedup.rnsort.test.bam     --primary_specific >(samtools view -bS - > "$PRIMARY"-specific.bam)     --secondary_specific >(samtools view -bS - > "$SECONDARY"-specific.bam)     --unassigned >(samtools view -bS - > "$DIR$SAMPLE"-unassigned.bam)
--------------------------------------------------------------------------------
Read Count Category Summary

|       Category                                     |     Count       |
|:--------------------------------------------------:|:---------------:|
|  primary_multi                                     |             29  |
|  primary_specific                                  |            377  |
|  secondary_multi                                   |              3  |
|  secondary_specific                                |             23  |
|  unresolved                                        |              8  |

```
However, when I use the --paired option (on the same data) I receive the following error:

```
xenomapper --primary_bam "$PRIMARY".merged.dedup.rnsort.test.bam     --secondary_bam "$SECONDARY".merged.dedup.rnsort.test.bam     --primary_specific >(samtools view -bS - > "$PRIMARY"-specific.bam)     --secondary_specific >(samtools view -bS - > "$SECONDARY"-specific.bam)     --unassigned >(samtools view -bS - > "$DIR$SAMPLE"-unassigned.bam)     --paired
Traceback (most recent call last):
  File "/home/561/lo6532/.local/bin/xenomapper", line 8, in <module>
    sys.exit(main())
  File "/home/561/lo6532/.local/lib/python3.7/site-packages/xenomapper/xenomapper.py", line 729, in main
    tag_func=tag_func)
  File "/home/561/lo6532/.local/lib/python3.7/site-packages/xenomapper/xenomapper.py", line 398, in main_paired_end
    for line1,line2 in readpairs:
  File "/home/561/lo6532/.local/lib/python3.7/site-packages/xenomapper/xenomapper.py", line 80, in getBamReadPairs
    assert line1[0] == line2[0]
AssertionError
```

Any help would be greatly appreciated :) Thanks!

**Comment by genomematt** [comment]
The error here is indicating the the expected interleaved forward and reverse reads is not occuring in the bam. Most frequently this is due to supplementary alignments. Try filtering to only primary alignments with `samtools view -F 256 input.bam` and see if that fixes your issue. Another alternative is that you may have reads that do not have a pair in your data. To keep only correctly mapping pairs use `samtools view -f 2 input.bam`
